FROM ubuntu:24.04

RUN apt-get update && apt-get install -y \
    curl \
    wget \
    gnupg \
    && curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y nodejs \
    && node --version \
    && npm --version

# Install Chromium
RUN apt-get install -y chromium-browser

RUN apt-get install -y \
        upower \
        libasound2t64=1.2.11-1build2 \
        libx11-xcb1 \
        libxcomposite1 libatk1.0-0 \
        libatk-bridge2.0-0 libcairo2 libcups2 \
        libdbus-1-3 libexpat1 libfontconfig1 \
        libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 \
        libnspr4 libpango-1.0-0 libpangocairo-1.0-0 \
        libstdc++6 libx11-6 libx11-xcb1 libxcb1 \
        libxcomposite1 libxcursor1 libxdamage1 \
        libxext6 libxfixes3 libxi6 libxrandr2 \
        libxrender1 libxss1 libxtst6 \
        libnss3 libgdk-pixbuf2.0-0

WORKDIR /app

COPY package.json yarn.lock ./
RUN npm install puppeteer
RUN npm install
COPY . .

CMD ["node", "index.js"]